#
#  █▀▀ █░█ █ █▀▀ █▄▀ █▀▀ █▄░█   █░░ █ █▀▀ █▀▀
#  █▄▄ █▀█ █ █▄▄ █░█ ██▄ █░▀█   █▄▄ █ █▀░ ██▄
#                                         by [SerumMC Developments] !
#                                            _
#                                   .-.  .--''` )
#                                _ |  |/`   .-'`
#                               ( `\      /`
#                               _)   _.  -'._
#                             /`  .'     .-.-;
#                             `).'      /  \  \
#                            (`,        \_o/_o/__
#                             /           .-''`  ``'-.
#                             {         /` ,___.--''`
#                             {   ;     '-. \ \
#           _   _             {   |'-....-`'.\_\
#          / './ '.           \   \          `"`
#       _  \   \  |            \   \
#      ( '-.J     \_..----.._ __)   `\--..__
#     .-`                    `        `\    ''--...--.
#    (_,.--""`/`         .-             `\       .__ _)
#            |          (                 }    .__ _)
#            \_,         '.               }_  - _.'
#               \_,         '.            } `'--'
#                  '._.     ,_)          /
#                     |    /           .'
#                      \   |    _   .-'
#                       \__/;--.||-'
#                        _||   _||__   __
#                 _ __.-` "`)(` `"  ```._)
#                (_`,-   ,-'  `''-.   '-._)
#               (  (    /          '.__.'
#                `"`'--'


Chicken: 
  Name: "&6Super Chicken Life"
  World-Name: "world"
  Loc-X: 1 
  Loc-Y: 2
  Loc-Z: 3
 
 
onClick:
  Messages: #When You click on supppper cl will send this mseeage to u soon will be clickable ! 
    - "Hi"
    - "Faq : 1"